# Generated by Django 4.2.3 on 2023-07-07 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coluna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('coluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban_back.coluna')),
            ],
        ),
        migrations.AddField(
            model_name='coluna',
            name='quadro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban_back.quadro'),
        ),
    ]
